# Generated by Django 4.1 on 2023-01-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
    ]
